# a_tensor_initialization.py

In [ ]:
이번 장은 tensor object에 대해 basic structure를 check해본다.

In [7]:
import torch

In [8]:
# torch.Tensor class
t1 = torch.Tensor([1, 2, 3], device='cpu')
print(t1.dtype)   # >>> torch.float32
print(t1.device)  # >>> cpu
print(t1.requires_grad)  # >>> False
print(t1.size())  # torch.Size([3])
print(t1.shape)   # torch.Size([3])
# 텐서 클래스는 float형 32비트나 int형 64비트를 주로 사용한다.
# 그중 여기서 쓰인 .Tensor클래스는 .FloatTensor와 같은 명령어다.
# requires_grad란 텐서 연산에서 역전파를 할 것인지의 여부이다.
# size 메서드나 shape 속성은 둘 다 텐서의 크기를 튜플로 반환한다.

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [12]:
# if you have gpu device
# t1_cuda = t1.to(torch.device('cuda'))
# or you can use shorthand
# t1_cuda = t1.cuda()
t1_cpu = t1.cpu()

In [13]:
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)  # >>> torch.int64
print(t2.device)  # >>> cpu
print(t2.requires_grad)  # >>> False
print(t2.size())  # torch.Size([3])
print(t2.shape)  # torch.Size([3])
#위와 달리 소문자로 이루어진 메서드이다.
# 리스트 내 원소 타입을 그대로 유지해준다고 한다.
# 추가적으로 말할게 있다면 cuda.tensor 등으로 이용하게 된다면 cpu가 아닌 gpu를 사용하게 된다.

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


- 위 코드에서 torch.tensor() 함수는 주어진 리스트내 원소 타입을 그대로 유지시켜 준다.

In [ ]:
t2_cpu = t2.cpu()

In [20]:
a1 = torch.tensor(1)			     # shape: torch.Size([]), ndims(=rank): 0
print(a1.shape, a1.ndim)
# 괄호가 없기에 텐서는 0차원으로 사이즈가 0이며 차원도 0이다.
a2 = torch.tensor([1])		  	     # shape: torch.Size([1]), ndims(=rank): 1
print(a2.shape, a2.ndim)
# 괄호가 있기에 텐서는 1차원으로 사이즈가 1이며 차원도 1이다.
a3 = torch.tensor([1, 2, 3, 4, 5])   # shape: torch.Size([5]), ndims(=rank): 1
print(a3.shape, a3.ndim)
# 괄호안에 5개의 요소를 가진 텐서이므로 사이즈는 5이며 차원은 1이다.
a4 = torch.tensor([[1], [2], [3], [4], [5]])   # shape: torch.Size([5, 1]), ndims(=rank): 2
print(a4.shape, a4.ndim)
# 1개의 괄호 안에 5개의 괄호가 있으며 각각 1개씩의 요소를 가지고 있으므로
# 사이즈는 [1,5,1]같지만 아니다. 
# 사이즈는 [5,1]이며 차원은 2이다.
# 주의하자.
a5 = torch.tensor([                 # shape: torch.Size([3, 2]), ndims(=rank): 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)
# 괄호 안에 3개의 괄호가 있고 2개씩 요소가 있으므로 크기는 [3,2]이고 차원은 2차원이다.

# 괄호의 개수는 차원의 수, 괄호 안에 요소의 개수는 크기

torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2


In [21]:
a6 = torch.tensor([                 # shape: torch.Size([3, 2, 1]), ndims(=rank): 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)
# 사이즈의 크기는 3개의 괄호, 1개씩의 요소이므로 [3,2,1]에 3의 차원을 가진다.
a7 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 1]), ndims(=rank): 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)
# 괄호가 4개 이므로 4차원이고 [3,1,2,1]의 크기를 가진다.
a8 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3]), ndims(=rank): 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)
# 괄호가 4개이므로 4차원이며, [3,1,2,3]의 크기를 가진다.

a9 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)
# 5개의 괄호이므로 5차원이며, [3,1,2,3,1]의 크기를 가진다.
a10 = torch.tensor([                 # shape: torch.Size([4, 5]), ndims(=rank): 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)
# 2개의 괄호이므로 2차원이고 5개의 요소가 있으므로 [4,5]의 크기를 가진다.
a10 = torch.tensor([                 # shape: torch.Size([4, 1, 5]), ndims(=rank): 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)
# 3개의 괄호 = 3차원, 크기는 [4,1,5]이다.
a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])
# 이 문법은 텐서의 문법에 맞지 않는다. 연산으로 가면 서로 다른 텐서의 구조라도 브로드캐스팅으로 연산이 되지만
# 텐서의 구축에서는 이와 같은 문법은 허용하지 않는다.
# 에러를 보면 3차원에 3개의 길이의 시퀀스를 예측했지만 2를 받았다고 뜬다.

torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


ValueError: expected sequence of length 3 at dim 3 (got 2)

### 여기서는 tensor의 구축 사용되는 list들을 통해 size와 dimension를 알 수 있게 되는 훈련을 할 수 있었다. 괄호의 개수는 차원의 개수고 사이즈의 크기는 스스로 추정하기 어렵다면 차원의 개수를 통해 추측할 수 있다.

# b_tensor_initialization_copy

이번 장은 배열이나 np로 tensor를 만드는 과정을 직접해본다.

In [22]:
import torch
import numpy as np

In [29]:
l1 = [1, 2, 3]
t1 = torch.Tensor(l1)
# 텐서 클래스로 float32의 타입을 따른다.
l2 = [1, 2, 3]
t2 = torch.tensor(l2)
# 텐서 메소드로 int64의 타입을 따른다.
l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)
# as_tensor 메소드는 넘파이(numpy) 배열, 리스트, 튜플 등과 같은 데이터를 PyTorch 텐서로 변환할 때 사용된다고 한다.
l1[0] = 100
l2[0] = 100
l3[0] = 100
# 텐서에 사용된 요소값을 변경한다.
print(t1)
print(t2)
print(t3)
# 하지만 이미 만들어진 텐서에는 적용되지 않는다.

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [30]:
print("#" * 100)

####################################################################################################


In [32]:
# 아래는 np 즉 넘파이를 사용한 텐서 만들기이다
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100
# 여기서도 텐서에 사용된 요소값을 변경한다.
print(t4)
print(t5)
print(t6,"ㅎ")
# 여기서는 t6의 출력에서 100으로 바뀜을 확인 할 수 있다.
# np로 만들어진 배열에서 as_tensor메소드를 거치면 텐서에 사용된 요소들을 추적함을 알 수 있다.

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([100,   2,   3], dtype=torch.int32) ㅎ


In [27]:
print(t6.dtype)

torch.int32


In [35]:
# 타입또한 int 32임을 알 수 있다.
# 그리고 np로 텐서를 만들게 되면 클래스가 아닌 메소드로 텐서 출력시 dtype가 기본적으로 같이 출력되는 것 같다.
l7 = np.array([1., 2, 3])
t7 = torch.as_tensor(l7)
l8 = np.array([1., 2, 3])
t8 = torch.Tensor(l8)
l8[0] = 100
# 여기서도 텐서에 사용된 요소값을 변경한다.
print(t8)

tensor([1., 2., 3.])


# c_tensor_initialization_constant_values

이번에는 tensor object의 메소드를 이용한 create이다.

In [36]:
import torch

In [48]:
t1 = torch.ones(size=(5,))  # or torch.ones(5)
# 1로 텐서를 구축한다. 여기서 사용되는 size는 5로 5개의 요소를 가진다.
# 유의해서 기억해야할 문법은 size=(5,)이다.
t1_like = torch.ones_like(input=t1)

print(t1)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like)  # >>> tensor([1., 1., 1., 1., 1.])

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])


In [55]:
tmp = [1,2,3,4,5]
tmp=torch.tensor(tmp)
tmp_like = torch.ones_like(input=tmp)
print(tmp)
print(tmp_like)
# 예상과 같이 기존의 텐서 구조에 대해서 1로 대체해서 출력함을 볼 수 있었다.

tensor([1, 2, 3, 4, 5])
tensor([1, 1, 1, 1, 1])


In [56]:
t2 = torch.zeros(size=(6,))  # or torch.zeros(6)
t2_like = torch.zeros_like(input=t2)
print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])
# zeros는 ones와 달리 0을 채워넣는 메소드이다.

tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])


In [39]:
t3 = torch.empty(size=(4,))  # or torch.zeros(4)
t3_like = torch.empty_like(input=t3)
print(t3)  # >>> tensor([0., 0., 0., 0.])
print(t3_like)  # >>> tensor([0., 0., 0., 0.])
# empty는 빈 공간을 말하는데 zeros메소드와 따른 점은 굳이 0이 아닌 아무 값이나 들어가도 된다는 점이다.
# 하지만 보통 0이 들어가는 편인듯 하다.

tensor([0., 0., 0., 0.])
tensor([6.8703e+09, 4.5912e-41, 1.0253e+12, 7.2868e-43])


In [59]:
t4 = torch.eye(n=3)
print(t4)
# eye는 뭐일까?
# 쉽게 예상할 수 없는 메소드이다.
# eye는 n*n의 전치행렬을 구축하는 메소드이다.
# 단 0과 1로만 이루어진 전치행렬인듯하다.
print(t4.dtype)
# 기본적으로 float32형을 따르는 듯 하다.

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
torch.float32


# d_tensor_initialization_random_values

이번 장에서는 랜덤한 tensor를 create하는 방법에 대해서 배운다.

In [62]:
import torch

In [63]:
t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)
# 랜덤한 int값 10에서부터 19까지의 수에서 사이즈가 1,2인 2차원 텐서
# high의 값이 미만인 것을 유의하자
# randint 메소드이다.
# 정수값만 추가된다.
t2 = torch.rand(size=(1, 3))
print(t2)
# 0부터 1까지의 수 중 사이즈가 1,3인 2차원 텐서
# 0부터 1까지의 수, 균등한 확률로 뽑힌다. 가 핵심이다.
t3 = torch.randn(size=(1, 3))
print(t3)
# 평균이 0이고 표준편차가 1인 수 중 사이즈가 1,3인 2차원 텐서
# 평균이 0이고 표준편차가 1인 수, 표준정규분포표 확률로 뽑힌다. 가 핵심이다.
t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)
# normal 메소드는 평균과 표준편차를 설정하여 텐서를 만들 수 있다.
t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)
# start 지접과 end 지점을 포함한 수에서 steps 개수가 나오도록 분할하여 텐서를 만든다.
t6 = torch.arange(5)
print(t6)
# 1차원 텐서를 반환하는데 start, end, steps을 매개변수로 가지며 end는 미포함한다.

tensor([[15, 16]])
tensor([[0.2671, 0.5633, 0.5580]])
tensor([[-1.8200, -1.9857,  0.0585]])
tensor([[ 9.4120, 12.1803],
        [ 8.3687, 11.4283],
        [10.8955,  9.1651]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])


In [64]:
print("#" * 30)

##############################


In [65]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)
# seed를 set하여 tensor를 create 할 수 있다.
random2 = torch.rand(2, 3)
print(random2)
# 두 tensor는 다른 값이 나오지만 밑에서 다시 seed를 설정한 뒤 다시 출력하면 같은 수가 나오게 된다.
print()

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


# e_tensor_type_conversion

이번 장에서는 type conversion에 대해서 배운다.

In [67]:
import torch

In [68]:
a = torch.ones((2, 3))
print(a.dtype)
# 사이즈가 2,3인 1로 이루어진 텐서 
b = torch.ones((2, 3), dtype=torch.int16)
print(b)
# 타입이 int16이면서 사이즈가 2,3인 1로 이루어진 텐서
c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)
# 타입이 flaot64이면서 0부터 1까지의 수가 uniform distribution을 따르는 2,3 사이즈의 텐서
# 이면서 각각의 값(요소)에 20씩 곱셈이 이루어지는 브로드케스팅이 적용된 연산
d = b.to(torch.int32)
print(d)
# 이미 만들어진 텐서에 to 메소드를 이용하여 int32의 자료형으로 바꿈

torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


## 아직 어떤 텐서만 출력시에 자료형까지 출력하는지 잘 모르겠다. 텐서만 출력하는데 자료형까지 출력이 되니 조금 당황스럽다.

In [73]:
double_d = torch.ones((10, 2), dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)
print(double_d)
print(short_e)
# 사이즈를 입력할 때 괄호를 안닫아도 된다는 것을 알게 되었다.
double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()
print(double_d)
print(short_e)
# 직접 자료형 메소드 입력하기
# double은 float64형
# short은 int16형
double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)
print(double_d)
print(short_e)
# to 메소드 이용하기
double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2). type(dtype=torch.short)
print(double_d)
print(short_e)
double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[1, 2]], dtype=torch.int16)
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16

# f_tensor_operations

이번 장은 tensor operation들에 대해서 공부한다.

In [74]:
import torch

In [75]:
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
# 더하기다.
t4 = t1 + t2
# 더하기다. 두 개 모두 다 자연스럽게 더해진다.
print(t3)
print(t4)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [79]:
t5 = torch.sub(t1, t2)
t6 = t1 - t2
# 빼기다.
# 둘 모두 자연스럽게 빼진다.
print(t5)
print(t6)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [80]:
t7 = torch.mul(t1, t2)
t8 = t1 * t2
# 곱하기다.
# 둘 모두 자연스럽게 곱해진다.
print(t7)
print(t8)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [81]:
t9 = torch.div(t1, t2)
t10 = t1 / t2
# 나누기다.
# 둘 모두 자연스럽게 나눠진다.
print(t9)
print(t10)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


# g_tensor_operations_mm

이번 장에서도 tensor operations의 matrix multiplication을 배워본다.
행렬 곱셈이다.

In [82]:
import torch

In [83]:
t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())
# 사이즈가 다른 두 텐서간 dot메소드는 dot 연산을 한다.
# 행렬의 dot 연산은 차원이 1이어야만 한다.
# 2*2 + 3*1 = 7이다.

tensor(7) torch.Size([])


In [84]:
t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3)
print(t4, t4.size())
# mm은 행렬 계산이다.
# 사이즈는 2,2가 나오게 된다.

tensor([[0.3775, 0.4037],
        [0.2384, 0.3181]]) torch.Size([2, 2])


In [86]:
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6)
print(t7.size())
# bmm은 batch 행렬계산이다.
# 10개의 행렬이 각각 3,4 사이즈이고, 4,5사이즈이다.
# 10개의 행렬은 각각 행렬 계산을 실행한다.

torch.Size([10, 3, 5])


# h_tensor_operations_matmul

matmul과 mul의 차이점은 행렬간 계산이냐, 요소간 계산이냐라는 차이라고 한다.
그리고 다른 mat이 붙은 연산에 대해서는 broadcasting이 적용된다는 점이 다르다.

In [7]:
import torch

In [16]:
# vector x vector: dot product
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())  # torch.Size([])
print(torch.matmul(t1,t2))
# 내적 연산으로 두 0차원의 수를 내적합니다.
tmp = torch.randn([3])

# rand에서 그냥 수만 적으면 0차원이다. 아니다. 그냥 적어도 1차원이다.
print(tmp.size())
print(t1.size())

torch.Size([])
tensor(-1.0056)
torch.Size([3])
torch.Size([3])


In [21]:
# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())  # torch.Size([3])
print(torch.matmul(t3,t4))
# 브로드 캐스팅이 적용된 내적연산이다.
# 자세히 보면 두 연산 대상의 사이즈가 다르지만 작은 사이즈가 큰 사이즈에 맞춰서 브로드 캐스팅되어 연산된다

torch.Size([3])
tensor([ 2.4175, -2.4718, -4.2049])


In [20]:
tmp1 = torch.ones((3,3))
tmp2 = torch.rand((3))

print(tmp1,tmp2,torch.matmul(tmp1,tmp2))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) tensor([0.4159, 0.2191, 0.5537]) tensor([1.1887, 1.1887, 1.1887])


In [36]:
# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])
# 사이즈가 10, 3, 4인 텐서에 4인 벡터를 연산하게되면 4 벡터는 3차원 텐서의 4와 계산되어 사라진다.
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(3)
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])
# 다른 수를 입력하게 되면 에러가 남을 확인할 수 있다.

torch.Size([10, 3])


RuntimeError: size mismatch, got 30, 30x4,3

In [11]:
# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])
# 배치 연산이다. 4가 사라지고 10 3 5만 남는다.

torch.Size([10, 3, 5])


In [12]:
# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])
# 위와 연산이 같다.

torch.Size([10, 3, 5])


# i_tensor_broadcasting

broadcasting이다.

In [22]:
import torch

In [23]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)
#텐서에 2.0이 각각 모두 곱해진다.

tensor([2., 4., 6.])


In [24]:
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4)
# 2차원 텐서에 1차원 텐서가 1차원에 각각 적용되어 빼진다.

tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])


In [25]:
t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # t5.add(2.0)
print(t5 - 2.0)  # t5.sub(2.0)
print(t5 * 2.0)  # t5.mul(2.0)
print(t5 / 2.0)  # t5.div(2.0)
# 2차원 텐서에 각각 브로드케스팅되어 연산된다.

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [26]:
def normalize(x):
  return x / 255

t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())
# 함수를 이용해서 브로드캐스팅을 자동화시켰다.

torch.Size([3, 28, 28])


In [27]:
t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]])
# 사이즈가 맞지 않는 tensor에서는 작은 tensor가 broadcasting되어 계산된다.

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])


In [28]:
t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape)
t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print(t14.shape)
t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape)
t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1
print((t17 + t18).size())
# 작은 차원에서부터 계산된다.
# 작은 값들은 큰값에 맞춰서 배수로서 채워지게되고 broadcasting되어 계산된다.

torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])


In [29]:
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])
t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])
t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])
# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

#여기서 t25와 t26은 각각 차원을 맞추고 싶어도 배수가 되지 않아서 runtime error가 나오게 된다.

torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])


In [30]:
t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])
t28 = torch.pow(t27, 2)
print(t28)  # >>> tensor([ 25, 25, 25, 25])
# pow메소드 또한 적용이 된다.
exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp)
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])
# 두 텐서간의 pow 메소드 적용이 가능하다.

tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1.,   4.,  27., 256.])


# j_tensor_indexing_slicing

수업시간에도 이해하기 어려웠던 슬라이싱 내용이다.

In [37]:
import torch

In [42]:
x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)
# 2차원의 텐서이다.
# 아래는 인덱싱에 관한 내용이다.
print(x[1])  # >>> tensor([5, 6, 7, 8, 9])
# 위의 텐서는 y축으로 생각하면 될 것 같다.
print(x[:, 1])  # >>> tensor([1, 6, 11])
# 위의 텐서는 y축에 대해서는 모든 값을 가져오지만 x 축에 대해서는 1의 인덱스를 가지는 값만 가져온다.
print(x[1, 2])  # >>> tensor(7)
# 위의 텐서는 y가 1, x가 2인 값을 가져온다.
print(x[:, -1])  # >>> tensor([4, 9, 14)
# 위의 텐서는 모든 y축에 대해서 -1인 값. 즉, x의 끝의 값을 가져온다.

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])


In [39]:
# 이제부터 슬라이싱이다.
print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])
# y축에 대해서 0이 아닌 1부터 모든 값을 가져온다.
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]])
# y축에 대해서 1부터의 값, x축에 대해서 3부터인 값을 가져온다.

tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])


In [40]:
y = torch.zeros((6, 6))
y[1:4, 2] = 1
print(y)
# y는 1부터 3까지의 값, x는 2인 값에 대해 1로 초기화하고
print(y[1:4, 1:4])
# y는 1~3까지의 값, x도 1~3까지의 값을 출력한다.

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])


In [41]:
z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
# 2차원 tensor이다.
print(z[:2])
# y축에 대해서 1까지의 값을 출력한다.
print(z[1:, 1:3])
# y축에 대해서 1부터의 값, x축에 대해서 1~2까지의 값을 출력한다.
print(z[:, 1:])
# 모든 y축에 대해서 x축은 1부터의 값을 출력한다.
z[1:, 1:3] = 0
# y축에 대해 1부터 모든 값, x축에 대해서 1부터 2까지의 값에 대해 0으로 초기화한다.
print(z)

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


# k_tensor_reshaping

텐서에 대한 재형성 내용이다. 이제부터는 메소드에 대한 설명을 요약하는 형식으로 주석을 달겠다.

In [43]:
import torch

In [44]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)  # Shape becomes (3, 2)
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6)
print(t2)
print(t3)
# view 메소드와 reshape 메소드는 tensor에 대해서 형태를 변경하는 메소드이다.
t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4)
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)
print(t4)
print(t5)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [54]:
# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])
# print(t6.size())
# Remove all dimensions of size 1
t7 = t6.squeeze()  # Shape becomes (3,)
# print(t6.size())


# squeeze 메소드는 차원을 삭제하는 메소드이다.
# 순간 헷갈렸지만 t6 tensor에 squeeze나 unsqueeze를 적용한다해도 t6 tensor에 직접 적용되는 것은 아니다.


# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1)
print(t7.size(),t7)
print(t8.size(),t8)

# 따라서 t7에서는 사이즈가 1인 모든 차원을 제거하고
# t8에서는 0차원인 tensor만 제거되어 1,3,1에서 3,1이 된다.

torch.Size([3]) tensor([1, 2, 3])
torch.Size([3, 1]) tensor([[1],
        [2],
        [3]])


In [46]:
# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

# Add a new dimension at position 1
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1)
print(t10)

# unsqueeze 메소드는 차원을 추가한다.
# 차원을 추가하여 3, 에서 3,1이 되었다.

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
# t11의 size는 2,3이다.
# 여기서 차원 1를 추가하는데 매개변수는 dim를 의미한다.

t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3)
print(t12, t12.shape)

tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])


In [47]:
# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor
t14 = t13.flatten()  # Shape becomes (6,)


# flatten 메소드는 다차원의 텐서를 1차원으로 만들어준다.

print(t14)

# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1)
# 여기서는 2,2,2인 텐서에서 1차원부터 flatten하겠다는 의미이다.

print(t16)
print(t17)

tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [72]:
t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])

# permute 메소드는 순서화시키다 라는 뜻을 가졌으며 view랑 동일한 효과를 갖는다고 수업시간에 들었다.
# 차원을 바꿔버린다? 이렇게 되면 출력이 어떻게 되는지 궁금하다.
tmp = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(tmp)
print(torch.permute(tmp, (1,2,0)))
# 좀 어렵게 바뀐다.

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])


In [73]:
# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becoms (3, 2)
print(t20)
print(t21)

# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)
# permute는 여러차원을 한번에 바꿀 수 있지만 transpose는 두 차원만 바꿀 수 있다.
print(t22)

t23 = torch.t(t19)  # Shape becomes (3, 2)
# transpose와 마찬가지로 두 개의 차원만 바꿀 수 있지만 얘는 2d tensor와 0차원과 1차원만 바꿀 수 있다.
print(t23)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


# l_tensor_concat

stacking 방법에 대해서 배운다.

In [74]:
import torch

In [75]:
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape)
# 차원에 대해서 스택처럼 붙이는 과정을 볼 수 있다.
# 1차원에 대해서 스택처럼 이어붙인 결과이다.

torch.Size([2, 6, 3])


In [76]:
t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])
# 두 텐서를 0차원으로 이어붙여서 1개의 텐서로 만들었다.
# 차원을 병합할 때 주의해야 할 점은 바로 해당 차원 수가 같아야 한다는 점이다.

torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [77]:
t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11]])

t11 = torch.cat((t8, t9), dim=1)
print(t11.size())  # >>>torch.Size([2, 6])
print(t11)
# >>> tensor([[ 0,  1,  2,  6,  7,  8],
#             [ 3,  4,  5,  9, 10, 11]])

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


In [78]:
t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11],
#             [12, 13, 14],
#             [15, 16, 17]])

t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)
# >>> tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#             [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])


In [79]:
t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5]],
#             [[ 6,  7,  8],
#              [ 9, 10, 11]]])

t20 = torch.cat((t17, t18), dim=1)
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5],
#              [ 6,  7,  8],
#              [ 9, 10, 11]]])

t21 = torch.cat((t17, t18), dim=2)
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)
# >>> tensor([[[ 0,  1,  2,  6,  7,  8],
#              [ 3,  4,  5,  9, 10, 11]]])

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


# m_tensor_stacking

stacking에 대한 공부를 배우자.

In [80]:
import torch

In [81]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])
#size 2,3

t3 = torch.stack([t1, t2], dim=0)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))
# 1,2,3 1,2,3 에서 2,2,3으로
t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))
# 2,1,3 2,1,3 에서 2,2,3으로
t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))
# 2,3,1 2,3,1 에서 2,3,2로 
# stack 메소드와 cat 메소드에 대해서 각각 사용법은 다르지만 같은 결과를 낼 수 있음을 보여주는 코드이다.

torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True


In [82]:
t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())
# >>> torch.Size([3]) torch.Size([3])

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  # >>> torch.Size([2,3])
print(t11)
# >>> tensor([[0, 1, 2],
#             [3, 4, 5]])

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))
# >>> True

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  # >>> torch.Size([3,2])
print(t13)
# >>> tensor([[0, 3],
#             [1, 4],
#             [2, 5]])
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))
# >>> True

# stack 메소드와 cat 메소드에 대해서 각각 사용법은 다르지만 같은 결과를 낼 수 있음을 보여주는 코드이다.

torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


# n_tensor_vstack_hstack

vstack과 hstack이 있는데 각각 행으로 열로 

In [83]:
import torch

In [84]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))
print(t3)
# >>> tensor([[1, 2, 3],
#             [4, 5, 6]])

t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))
# >>> tensor([[1],
#             [2],
#             [3],
#             [4],
#             [5],
#             [6]])

# vstack메소드이기에 3,1 이 6,1 이 되었다.

tensor([[1, 2, 3],
        [4, 5, 6]])


In [85]:
t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)
# >>> (2, 2, 3)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)
# >>> (2, 2, 3)

t9 = torch.vstack([t7, t8])
print(t9.shape)
# >>> (4, 2, 3)

print(t9)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6]],
#             [[ 7,  8,  9],
#              [10, 11, 12]],
#             [[13, 14, 15],
#              [16, 17, 18]],
#             [[19, 20, 21],
#              [22, 23, 24]]])

# 위 코드도 합쳐졌다.
# 합쳐지는 것을 보아 0차원이 합쳐지는 것 같다.

torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])


In [86]:
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
print(t12)
# >>> tensor([1, 2, 3, 4, 5, 6])

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)
# >>> tensor([[1, 4],
#             [2, 5],
#             [3, 6]])

t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)
# >>> (2, 2, 3)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)
# >>> (2, 2, 3)

t18 = torch.hstack([t16, t17])
print(t18.shape)
# >>> (2, 4, 3)

print(t18)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6],
#              [13, 14, 15],
#              [16, 17, 18]],
#             [[ 7,  8,  9],
#              [10, 11, 12],
#              [19, 20, 21],
#              [22, 23, 24]]])

# hstack 메소드는 1차원이 합쳐지는 듯 하다.

tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


# 숙제 후기
본 숙제를 한 이후의 느낀점, 
하고싶은 말, 또는 불

우선적으로 수업 외적으로 코드를 돌아보면서 수업 때 이해했던 것이라도 다시보니 조금 낯설 때가 많았다.
러닝에서 tensor 객체가 가장 기본이 되고 이를 어떻게 활용하는가?가 딥러닝의 기초가 됨을 알게 되었고
tensor를 내 입맛에 맞게 수정하기 위해서는 다양한 메소드들을 활용해야하는데 이를 완전히 기억하기에는 아직 무리가 좀 있다.
이제 메소드들을 알게 되었으니 이 메소드들을 적재적소에 사용하면서 코드에 익숙해져야만 할 것 같다.

중간중간 모르겠는 내용들은 검색을 통해 해소하였고 제가 시험하기 위해 사용한 코드들과 coment들로 주석을 달았는데 교수님이 원하는 바를 이렇게 작성해도 될 지 궁금합니다.평